def buildings_dict():
    bdict = {
    'ABA': 'Anna Bing Arnold Child Care Ctr., 2715 University Ave.',
    'ABM': 'American Button Manufacturing, 2823 S. Flower St.',
    'ABX': 'Anna Bing Arnold Child Care Ctr. Annex, 2716 Severance St., 90007',
    'ACB': 'Ahmanson Ctr. for Biological Research, 825 Bloom Walk',
    'ACC': 'Accounting, Leventhal School of, 3660 Trousdale Pkwy.',
    'ACX': 'Ahmanson Ctr. for Biological Research Animal Section, 825 Bloom Walk',
    'ADM': 'George Finley Bovard Administration Bldg. and Kenneth Norris, Jr. Aud., 3551 Trousdale Pkwy.',
    'ADX': 'Alpha Delta Chi House, 725-731 W. 32nd St.',
    'AEP': 'Alpha Epsilon Pi fraternity, 904 W. 28th St.',
    'AES': 'Alice and Eleonore Schoenfeld Symphonic Hall, 3450 Watt Way',
    'AGO': 'Gamma Epsilon Omega fraternity, 2831 University Ave.',
    'AHF': 'Allan Hancock Foundation Bldg., 3616 Trousdale Pkwy.',
    'AHN': 'Dosan Ahn Chang Ho Family House, 809 W. 34th St.',
    'ALM': 'Alumni House, Widney, 635 Childs Way',
    'ANH': 'Annenberg House, 711 W. 27th St.',
    'ANN': 'Wallis Annenberg Hall, 3630 Watt Way',
    'ASC': 'Annenberg School for Communication and Journalism, 3502 Watt Way',
    'ATM': 'At Mateo, 1262 Palmetto St., Ste. 515',
    'BAA': 'Bel-Aire Apts., 1124 W. 29th St.',
    'BAB': 'Barracks A & B, 1200 N. State St.',
    'BAR': 'Barlow Hospital, 2000 Stadium Way',
    'BCC': 'Eli and Edythe Broad CIRM Center for Regenerative Medicine and Stem Cell Research, 1425 San Pablo St.',
    'BCH': 'Boone Center Housing, 10317-10343 W. Big Fishermans Cove, Catalina Island',
    'BDF': 'Brooks Memorial Pavilion and Dedeaux Field, 1021 Childs Way',
    'BHE': 'Biegler Hall of Engineering, 920 Downey Way',
    'BIM': 'Brittingham Intramural Field, 3506 McClintock Ave.',
    'BIT': 'Bing Theatre, 3500 Watt Way',
    'BKF': 'Brian Kennedy Field, 3515 McClintock Ave.',
    'BKS': 'Pertusati University Bookstore, 840 Childs Way',
    'BMH': 'Booth Ferris Rehearsal Hall, 820 W. 34th St.',
    'BMP': 'Burbank Medical Plaza #2, 191 S. Buena Vista St., #310, Burbank',
    'BMT': 'Bishop Medical Teaching and Research Bldg., 1333 San Pablo St.',
    'BRI': 'Barrack Hall, 3670 Trousdale Pkwy.',
    'BSR': 'Birnkrant Residential College, 642 W. 34th St.',
    'BTP': 'Beta Theta Pi fraternity, 2714 Portland St.',
    'CAB': 'CMSC Administration Bldg., P.O. Box 398, Catalina Island, 90704',
    'CAL': 'Carole Little Bldg., 3434 S. Grand Ave.',
    'CAP': 'Century Apts., 3115 S. Orchard Ave.',
    'CAR': 'Cardinal Gardens, 3131 S. McClintock Ave.',
    'CAS': 'College Academic Services Bldg., 3454 Trousdale Pkwy.',
    'CBB': 'Century Boulevard Building, 6033 Century Blvd. #920, Los Angeles',
    'CBG': 'University Gardens Apts., 1250 W. Jefferson Blvd.',
    'CCC': 'Health Sciences Child Care Ctr., 2250 Alcazar St.',
    'CDF': 'Campus Development & Facilities Bldg., 3434 Grand Ave.',
    'CEM': 'Ctr. for Electron Microscopy and Microanalysis, 814 W. Bloom Walk',
    'CEN': 'Centennial Apts., 2390 Portland St.',
    'CFH': 'Dean Bartlett Cromwell Field House, 3525 Watt Way',
    'CHP': 'Ctr. for Health Professions, 1540 Alcazar St.',
    'CIC': 'Jessica and Charles Cale and Ray Irani Residential College, 929 W. Jefferson Blvd.',
    'CLH': 'College House, 823 W. 34th St.',
    'CNG': 'Cardinal ’N Gold, 737 W. 30th St.',
    'COH': 'Cockins House, 2653 S. Hoover St.',
    'COL': 'College Residence Hall, 615 W. McCarthy Way',
    'CRC': 'A.C. Allen Cowlings and Ilium Residential College, 3131 S. Hoover St.',
    'CRL': 'Cancer Research Laboratory, 1303 Mission Rd.',
    'CSA': 'Clinical Sciences Annex, 2250 Alcazar St.',
    'CSC': 'Clinical Science Ctr., 2250 Alcazar St.',
    'CST': 'CAD Services Trailer, Berth 194 Yacht St., Wilmington',
    'CTV': 'Carson Television Ctr., 3450 Watt Way',
    'CUB': 'Credit Union Building, 3720 S. Flower St.',
    'DCC': 'Davidson Continuing Education Conference Ctr., 3415 S. Figueroa St.',
    'DCF': 'Delta Chi fraternity, 920 W. 28th St.',
    'DEN': 'Norris Dental Science Ctr., 925 W. 34th St.',
    'DML': 'Doheny Memorial Library, 3550 Trousdale Pkwy.',
    'DMT': 'Marks Tower, 612 W. Hellman Way',
    'DNI': 'Dornsife Neuroscience Imaging Center, 3620-A McClintock Ave.',
    'DOH': 'Estelle Doheny Eye Foundation, 1355 San Pablo St.',
    'DRB': 'Denney Research Ctr., 1042 Downey Way',
    'DRC': 'Drama Ctr., 1029-33 Childs Way',
    'DXM': 'Marks Residence Hall, David X., 631 W. Childs Way',
    'ECT': 'Early Childhood Training Ctr., 741 W. 27th St.',
    'EDM': 'Edmondson Research Bldg., 1840 N. Soto St.',
    'EEB': 'Hughes Aircraft Electrical Engineering Center, 3740 McClintock Ave.',
    'EGG': 'Egg Company II, 746 W. Adams Blvd.',
    'ELB': 'East Library Bldg., 3440 S. Hope St.',
    'EPS': 'Figueroa Street Structure, 3533 S. Flower St.',
    'ESH': 'Engemann Student Health Center, 1031 W. 34th St.',
    'EVK': 'EVK Residence Hall, 635 W. McCarthy Way',
    'FIG': 'Figueroa Bldg., 3535 S. Figueroa St.',
    'FLT': 'Fluor Tower, 1027 W. 34th St.',
    'FMH': 'Forthmann House, 2801 South Hoover St.',
    'FML': 'Feuchtwanger Memorial Library, 520 Paseo Miramar, Pacific Palisades',
    'FMT': 'Fairmont Apts., 2629 Portland St.',
    'FPM': 'Facilities Management & Planning Trailer, 3450 S. Vermont Ave.',
    'FRE': 'Freeman House, 1962 Glencoe Way',
    'FSA': 'Founders Apts., 2610 Portland St.',
    'GAH': 'Gamble House, 4 Westmoreland Pl., Pasadena',
    'GAP': 'Galen Athletic Pavilion, 3400 S. Figueroa St.',
    'GEC': 'Galen Event Center, 3400 S. Figueroa St.',
    'GEH': 'Max Kade Ctr. I, 2714 S. Hoover St.',
    'GER': 'Gerontology Ctr., Andrus, 3715 McClintock Ave.',
    'GEX': 'Max Kade Ctr. II, 2718 S. Hoover St.',
    'GFS': 'Grace Ford Salvatori Hall of Letters, Arts and Sciences, 3601 Watt Way',
    'GLB': 'General Labs Bldg., 1129 N. State St.',
    'GNH': 'County General Hospital, 1937 Hospital Pl.',
    'GPC': 'Golf Practice Course, 1021 Childs Way',
    'HAP': 'Helena Apts., 1220 W. 28th St.',
    'HAR': 'Mary Ormerod Harris Hall, Quinn Wing and Fisher Gallery, 823-29 Exposition Blvd.',
    'HC1': 'USC Health Care Consultation Ctr., 1510 San Pablo St.',
    'HC2': 'Health Care Consultation Ctr. 2, 1520 San Pablo St.',
    'HC3': 'Norris Health Care Consultation Ctr., 2204 Alcazar St.',
    'HC4': 'Estelle Doheny Eye Institute, 1537 Norfolk St.',
    'HCB': 'CMSC Hyperbaric Chamber Building, P.O. Box 398, Catalina Island, Avalon',
    'HED': 'HEDCO Petroleum & Chemical Engineering Bldg., 925 Bloom Walk',
    'HER': 'Heritage Hall, 3501 Watt Way',
    'HHR': 'Honors House, 2710 Severance St.',
    'HIL': 'Hillview Apts., 2605 Severance St.',
    'HJF': 'Howard Jones Football Practice Field, 3515 McClintock Ave.',
    'HMR': 'Hoffman Medical Research Ctr., 2011 Zonal Ave.',
    'HNB': 'HEDCO Neurosciences Bldg., 3641 Watt Way',
    'HOH': 'Hoffman Hall of Business Administration, 701 Exposition Blvd.',
    'HPB': 'Huntington Pavilion Bldg., 625 Fair Oaks Ave., Suite 400, Pasadena',
    'HRA': 'Health Research Assn., 1640 Marengo St.',
    'HRH': 'Harris Residence Hall, 634 W. 34th St.',
    'HSA': 'Health Sciences Alhambra, 1000 S. Fremont Ave., Alhambra, CA',
    'HSH': 'Hazel and Stanley Hall Financial Services Bldg., 851 Downey Way',
    'HSP': 'Health Sciences Campus Parking Structure, 1334 Biggy St.',
    'HSR': 'Hoover Street Residence, 2827 Hoover St.',
    'HUC': 'Hebrew Union College, 3077 University Ave.',
    'IFT': 'Ickovics Family Trust Bldg. Fine Arts, 3001 S. Flower St.',
    'IRC': 'Internationally Themed Residential College, 3771 McClintock Ave.',
    'IRD': 'Interns & Residents Dormitory, 2020 Zonal Ave.',
    'ISE': 'Information Science Institute East, 3811 N. Fairfax Dr., Arlington, VA',
    'ISI': 'Information Science Institute, 4676 Admiralty Way, Marina del Rey',
    'IYH': 'USC Jimmy Iovine and Andre Young Hall, 3738 Watt Way',
    'JEF': 'Jefferson Bldg., 950 W. Jefferson Blvd.',
    'JEP': 'Joint Educational Project House, 801 W. 34th St.',
    'JFF': 'Jill and Frank Fertitta Hall, 610 Childs Way',
    'JHH': 'John Hubbard Hall, Student Administrative Services, 700 Childs Way',
    'JKP': 'Jane Popovich and J. Kristoffer Popovich Hall, 611 Exposition Blvd.',
    'JMC': 'John McKay Ctr., 940 W. 35th St.',
    'JWS': 'John Williams Scoring Stage, 3450 Watt Way',
    'KAM': 'Keith Administration & Medical Forum Bldg.; Mayer Medical Teaching Ctr., 1975 Zonal Ave.',
    'KAP': 'Kaprielian Hall, 3620 S. Vermont Ave.',
    'KCH': 'Kerckhoff Carriage House, 734 W. Adams Blvd.',
    'KDC': 'Glorya Kaufman International Dance Center, 849 W. 34th St.',
    'KER': 'Kerckhoff Hall, 734 W. Adams Blvd.',
    'KOH': '1025 W. 34th St.',
    'KSH': 'University Club at King Stoops Hall, 705 W. 34th St.',
    'LAB': 'La Sorbonne Apts., 1170 W. 31st St.',
    'LAC': 'Los Angeles County + USC Hospital, 1200 N. State St.',
    'LAW': 'Elvon and Mabel Musick Law Bldg., 699 Exposition Blvd.',
    'LCA': 'Lambda Chi Alpha fraternity, 720 W. 28th St.',
    'LHI': 'Donald P. and Katherine B. Loker Hydrocarbon Inst., 837 Bloom Walk',
    'LJS': 'Laird J. Stabler Memorial Hall, 840 Downey Way',
    'LRA': 'Livingston Research Annex, 1321 N. Mission Rd',
    'LRB': 'Livingston Research Building, 1321 N. Mission Rd',
    'LRC': 'General William Lyon University Ctr., 1026 W. 34th St.',
    'LTS': 'Katherine B. Loker Track Stadium, 3550 McClintock Ave.',
    'LVL': 'Thomas and Dorothy Leavey Library, 650 W. McCarthy Way',
    'MAB': 'Manor Apts., 2636 Portland St.',
    'MBC': 'MacDonald Becket Center, 850 W. Bloom Walk',
    'MCA': 'McKibben Addition, 1333 San Pablo St.',
    'MCB': 'Michelson Center For Convergent Bioscience, 1002 Childs Way',
    'MCC': 'McClintock Building, 1010 W. Jefferson Blvd.',
    'MCH': 'McKibben Hall, 1333 San Pablo St.',
    'MCK': 'McClintock Apartments Building Two, 1082 30th St.',
    'MCO': 'McClintock Apartments Building One, 1076 30th St.',
    'MCT': 'McCulloch Townhomes, 953 W. 30th St.',
    'MHC': 'The Kathleen L. McCarthy Honors College, 3096 S. McClintock Ave.',
    'MHP': 'Mudd Memorial Hall of Philosophy, 3709 Trousdale Pkwy.',
    'MMR': 'Mudd Memorial Research Bldg., 1333 San Pablo St.',
    'MOL': 'Medical Oncology Lab, 1237 N. Mission Rd.',
    'MRC': 'Priam Residential College, 835 W. Jefferson Blvd.',
    'MRF': 'Montgomery Ross Fisher Bldg., 669 W. 34th St.',
    'MRI': 'Magnetic Resonance Imaging Building, 2025 Zonal Ave.',
    'MSC': 'Marine Sciences Ctr. Lab, Catalina Island',
    'MSR': 'Marine Sciences Center Residence Hall, Catalina Island',
    'MTX': 'Marks Tennis Stadium, 1075 Childs Way',
    'MUS': 'Albert S. Raubenheimer Music Faculty Memorial Bldg., 840 W. 34th St.',
    'NBC': 'Shelly and Ofer Nemirovsky and David C. Bohnett Residential College, 3201 S. Hoover St.',
    'NCT': 'Norris Cinema Theatre, 3507 Trousdale Pkwy.',
    'NLC': 'Norman Lear Center, 8383 Wilshire Blvd. #652',
    'NML': 'Norris Medical Library, 2003 Zonal Ave.',
    'NOR': 'Kenneth Norris Jr. Cancer Hospital Research Institute, 1441 Eastlake Ave.',
    'NRT': 'Harlyne J. Norris Research Tower, 1450 Biggy St.',
    'NTT': 'Dr. Norman Topping Tower, 1441 Eastlake Ave.',
    'OCC': 'Orange County Campus, 2300 Michelson Dr., Irvine, 92714',
    'OCW': 'Harold E. and Lillian M. Moulton Organic Chemistry Wing, 810 Downey Way',
    'OHE': 'Olin Hall of Engineering, 3650 McClintock Ave.',
    'ONE': 'One Institute, 909 W. Adams Blvd.',
    'OSP': 'Our Savior Parish and USC Caruso Catholic Center, 844 W. 32nd St.',
    'PAM': 'Pacific Asia Museum, 46 N. Los Robles Ave., Pasadena',
    'PCA': 'Pacific Apts., 2637 Severance St.',
    'PCE': 'Petroleum and Chemical Engineering Bldg., 923 Bloom Walk',
    'PED': 'Physical Education Bldg., 3560 Watt Way',
    'PHE': 'Powell Hall, 3737 Watt Way',
    'PHH': 'Phinney Hall, 1721 Griffin Ave.',
    'PKS': 'Parkside Apts., 3730 S. McClintock Ave.',
    'PRB': 'Parkside Residential Building, 920 West 37th Place',
    'PSA': 'Downey Way Structure, Lot 33, 3667 McClintock Ave.',
    'PSB': 'Jefferson Boulevard Structure, Lot 1, 1150 Jefferson Blvd.',
    'PSC': 'John Stauffer Pharmaceutical Sciences Ctr., 1985 Zonal Ave.',
    'PSD': 'Royal Street Structure, 649 W. 34th St.',
    'PSO': 'Flower Street Structure, 3701 S. Flower St.',
    'PSX': 'McCarthy Way Structure, 620 W. McCarthy Way',
    'PTD': 'Pardee Tower, 614 Hellman Way',
    'PVB': 'Playa Vista Bldg., 12015 E. Waterfront Dr., Playa Vista',
    'PVT': 'Playa Vista Bldg. Two, 12025 Waterfront Dr., Playa Vista',
    'RAN': 'Hoffman Contracts Research Bldg., 3716 S. Hope St.',
    'RGA': 'Regent Apts., 1138 W. 29th St.',
    'RGL': 'Ralph and Goldy Lewis Hall, 650 Childs Way',
    'RHM': 'Ramo Hall of Music, 830 W. 34th St.',
    'RHR': 'Radisson Hotel Restaurant, 3520 S. Figueroa St.',
    'RMH': 'Radisson Midcity Hotel, 3540 S. Figueroa St.',
    'RRB': 'Rapp Engineering Research Bldg., 854 Downey Way',
    'RRI': 'Ray R. Irani Hall, 1050 Childs Way',
    'RTA': 'Regal Trojan Apts., 870 W. Adams Blvd.',
    'RTH': 'Ronald Tutor Hall of Engineering, 3710 McClintock Ave.',
    'RZC': 'Robert Zemeckis Ctr. for Digital Arts, 3131 S. Figueroa St.',
    'SAC': 'Sacramento Center, 1800 I Street, Sacramento, CA',
    'SAI': 'Stardust Apts., 634 W. 27th St.',
    'SAL': 'Salvatori Computer Science Ctr., 941 Bloom Walk',
    'SCA': 'School of Cinematic Arts, 900 W. 34th St.',
    'SCB': 'School of Cinematic Arts Bldg. B, 930 W. 34th St.',
    'SCC': 'School of Cinematic Arts Bldg. C, 935 W. 35th St.',
    'SCD': 'Scene Dock (Theatre), 1030 W. 37th St.',
    'SCE': 'School of Cinematic Arts Bldg. E, 905 W. 35th St.',
    'SCI': 'School of Cinematic Arts Bldg. I, 3470 McClintock Ave.',
    'SCO': 'USC Building One, 1149 S. Hill St.',
    'SCP': 'South Coast Plaza Bldg., 3333 Bristol St., Costa Mesa',
    'SCS': 'School of Cinematic Arts Station, 639 W. 32nd St.',
    'SCT': 'USC Building Two, 1150 S. Olive St.',
    'SCX': 'School of Cinematic Arts Bldg. D, 915 W. 35th St.',
    'SGA': 'Seven Gables Apts., 620-626 W. 30th St.',
    'SGM': 'Seeley G. Mudd Bldg., 3620 McClintock Ave.',
    'SHN': 'Stevens Hall Neuroimaging, 2025 Zonal Ave.',
    'SHP': 'Shrine Parking Structure, 645 W. Jefferson Blvd.',
    'SHS': 'Stauffer Hall of Science, 835 Bloom Walk',
    'SIE': 'Sierra Apts., 2638 Portland St.',
    'SKS': 'Steven and Kathryn Sample Hall, 3607 Trousdale Pkwy.',
    'SLH': 'Stauffer Science Lecture Hall, 831 Bloom Walk',
    'SMF': 'Soni-McAlister Field, 3000 S. Hoover St.',
    'SNA': 'Senator Apts., 1101-1109 W. 28th St.',
    'SOS': 'Social Science Bldg., 3502 Trousdale Pkwy.',
    'SPA': 'Shrine Place Apartments, 3015-3017 Shrine Pl.',
    'SPS': 'San Pablo Parking Structure, 1630 N. San Pablo St.',
    'SRH': 'Seaver Residence Hall, 1969 Zonal Ave.',
    'SSA': 'Severance St. Apts., 2630 Severance St.',
    'SSB': 'Soto Street Building, 2001 N. Soto St.',
    'SSC': 'Seaver Science Ctr., 920 Bloom Walk',
    'SSH': 'Severance St. House, 2716 Severance St.',
    'SSL': 'Seaver Science Library, 910 Bloom Walk',
    'SST': 'Soto Street Building Two, 2011 Soto St.',
    'STO': 'Stonier Hall, 837 Downey Way',
    'STU': 'Gwynn Wilson Student Union, 3601 Trousdale Pkwy.',
    'SUN': 'Sunset Apts., 1144 W. 29th St.',
    'SWC': 'Social Work Ctr., 655 W. 34th St.',
    'TAP': 'Troyland Apts., 955-959 W. Adams Blvd.',
    'TCC': 'Ronald Tutor Campus Center, 3607 Trousdale Pkwy.',
    'TCX': 'Tennis Court I, 1015 Childs Way',
    'TGF': 'Town and Gown, 665 Exposition Blvd.',
    'THH': 'Taper Hall of Humanities, 3501 Trousdale Pkwy.',
    'THR': 'Two Harbors Residences, Two Harbors, Catalina Island',
    'TMC': 'The Music Complex, 3450 Watt Way',
    'TOW': 'Tower Hall, 1711 N. Griffin Ave.',
    'TPA': 'Twin Palms Apts., 2635 Portland St.',
    'TRF': 'Temporary Research Facility, 3430 S. Vermont Ave.',
    'TRH': 'Troy Hall, 3025 Royal St.',
    'TRO': 'Trojan Residence Hall, 615 Childs Way',
    'TSA': 'Terrace Apts., 2822-2830 Ellendale Pl.',
    'TTL': 'Technical Theatre Lab., 1020 Bloom Walk',
    'TUS': 'Tuscany, 3760 S. Figueroa St.',
    'TYL': 'Tyler Bldg., 3601 S. Flower St.',
    'UAC': 'Uytengsu Aquatics Center, 3441 McClintock Ave.',
    'UGB': 'University Gardens Building, 3500 S. Figueroa St.',
    'UGW': 'University Gateway, 3335 S. Figueroa St.',
    'UHP': 'University Hosp. Parking, 1538 San Pablo St.',
    'UNH': 'USC University Hosp., 1500 San Pablo St.',
    'UPX': 'Grand Avenue Structure, 3401 S. Grand Ave.',
    'URA': 'University Regent Apts., 1219 W. 27th St.',
    'URC': 'University Religious Ctr., 835 W. 34th St.',
    'URH': 'University Residence Hall, 616 W. 34th St.',
    'UUC': 'United University Church, 817 W. 34th St.',
    'UVO': 'University Village One, 3015 S. Hoover St.',
    'VBB': 'Valley Blvd. Bldg., 4351 E. Valley Blvd.',
    'VHE': 'Vivian Hall of Engineering, 3651 Watt Way',
    'VHH': 'Verdugo Hills Hospital, 1812 Verdugo Blvd.',
    'VIS': 'Vista Apts., 2701 Severance St.',
    'VKC': 'Von KleinSmid Ctr. for International and Public Affairs, 3518 Trousdale Pkwy.',
    'VPD': 'Verna & Peter Dauterive Hall, 635 Downey Way',
    'VWB': 'Valley Warehouse Bldg., 4121 Valley Blvd.',
    'WAH': 'Watt Hall of Architecture and Fine Arts, 850 Bloom Walk',
    'WIN': 'Windsor Apts., 1149 W. 28th St.',
    'WPH': 'Waite Phillips Hall, 3470 Trousdale Pkwy.',
    'WTO': 'Webb Tower, 1015 W. 34th St.',
    'ZHS': 'Zumberge Hall of Science, 3651 Trousdale Pkwy.',
    'ZNI': 'Zilkha Neurogenetic Institute, 1501 San Pablo St.'
    }
    return bdict
